name: enhanced_table_calendar
description: Highly customizable, feature-packed calendar enhanced widget for Flutter.
version: 3.1.0
author: Davide Andreossi <dandreossi@gmail.com>
homepage: https://github.com/dandreossi/enhanced_table_calendar
note: This is a fork of the original table_calendar package by aleksanderwozniak

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
